# Generated by Django 6.0.5 on 2026-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ ]

    operations = [
        migrations.CreateModel(
            name='ToDolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='описание')),
                ('status', models.CharField(max_length=300, verbose_name='статус')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='дата выполнения')),
            ],
            options={
                'verbose_name': 'задача',
                'db_table': 'todolist',
            },
        )
    ]
