# Generated by Django 6.0.5 on 2026-05-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_todolist_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='more_detailed_description',
            field=models.TextField(blank=True, null=True, verbose_name='более подробное описание'),
        ),
    ]
